### ISSUE TITLE
Notification pop-ups are only working on the Pixel3 XL API 29 emulator

### ISSUE THREAD

**Issue by serb2341** [Sudhan-Dahake/CalamityCall#10] opened 2024-10-19 17:09 UTC
The notification pop-ups are only appearing when the Pixel3 XL API 29 emulator is used. When any other emulator is used, the notification does not appear on the screen.

**Comment by hsihak** [comment] 2024-10-22 14:23
The root cause was a mistyped _channel ID_, which prevented notifications from appearing properly across different devices. The channel ID has now been corrected to **"channel1"** for consistency. As a result, notifications are functioning as expected on all tested devices and emulators.

**Device Tested on:**

![image](https://github.com/user-attachments/assets/cab38f7c-274c-4b67-a180-b55ce61e7f0a)

**Before and After Changes:**
![image](https://github.com/user-attachments/assets/a58ec99d-508b-49c3-9239-41c5f8ad0c9c)

Please try out the changes, and if they meet your expectations, feel free to close the issue. Thanks! ✨

**Comment by hsihak** [comment] 2024-10-25 21:21
This issue has been resolved by updating the notification channel ID to "**channel1**," ensuring consistency across different devices and emulators. Notifications are now appearing as expected after thorough testing on multiple devices.

Please note that **Android 13 and 14** require explicit user permission for notifications, which influenced the initial compatibility. For future builds, make sure the app requests notification permissions as outlined in the [Android documentation](https://developer.android.com/develop/ui/views/notifications/notification-permission).

**Comment by hsihak** [comment] 2024-10-31 15:21
Notifications does not work on API 34 and above! 😭

**Comment by hsihak** [comment] 2024-11-04 16:20
Resolved!

**Closed by hsihak** 2024-11-04 16:20 UTC
Labels: bug, enhancement
